name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the action on push events to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Transaction-Project  # Navigate to the project directory
          git pull origin main  # Pull latest changes
          
          # Navigate to server, install dependencies, and restart it
          cd server
          npm install
          
          # Ensure pm2 is installed globally
          sudo npm install pm2 -g
          pm2 restart transaction-web
          
          # Navigate to client, install dependencies, and build it
          cd ../Client
          rm -rf build
          sudo npm install -g yarn
          yarn install
          yarn build || exit 1
          sudo nginx -t
          sudo systemctl restart nginx
